Flow control and loops
f0rsakenOne/home-excercises pull request #2
Opened 2022-02-28 15:16 UTC by f0rsakenOne

Finished all flow control and loops exercises.

2022-03-05 22:39 UTC, janistumpelis requested changes

2022-03-05 22:39 UTC, janistumpelis commented on src/main/java/io/codelex/flowcontrol/exercises/PhoneKeyPad.java
> +        if (in.hasNextInt()||in.hasNextDouble()){
Šis īsti nebūs korektākais veids kā pārbaudīt input, drīzak var nolasīt lietotāja input un tad pārbaudīt vai tas string atbilst regex. Piemēram šādi:
`phoneLetters.matches("[a-z|#|*|\\s]*");`

2022-03-05 22:39 UTC, janistumpelis commented on src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +
Šis nav jālabo, bet uz priekšdienām neatstāj tik lielas atstarpes starp koda rindām.

2022-03-05 22:39 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/FizzBuzz.java
> +            if (j % 20 == 0 && j % 3 == 0) {
Šie IF kaut kā dīvaini uzrakstīti. Vai pareizāk - pāris IF ir lieki.
Faktiski ir tā - ja j%3 ==0, tad jāizdrukā ir Fizz, ja j%5==0, tad jāizdrukā ir Buzz, ja j%3==0 un j%5==0, tad jāizdrukā ir FizzBuzz un else => izdrukā pašu skaitli. Pēc tam atsevišķa IF pārbaudi vai j%20 == 0 un, ja ir, tad System.out.println() izdrukās jaunas rindas simbolu.

2022-03-05 22:39 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/NumberSquare.java
> +        for (int i = min;i<=max;i++){
Kods izskatās nav noformatēts.

2022-03-05 22:39 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Piglet.java
> +                System.out.println("You got "+score+" points.");
Šī rindiņa faktiski 2x atkārtojas - šeit un 21. rindā.
Korektāk būtu to score izvadīt pēc while cikla, nevis pašā cīklā divreiz rakstīt to rindiņu.

2022-03-06 15:23 UTC, f0rsakenOne commented on src/main/java/io/codelex/flowcontrol/exercises/PhoneKeyPad.java
> +        if (in.hasNextInt()||in.hasNextDouble()){
mainīts tā, lai input būtu pirms if, kurā notiek pati pārbaude

2022-03-06 15:25 UTC, f0rsakenOne commented on src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +
jā, aizmirsu par to, ka vajag dzēst tukšās rindas ¯\_(ツ)_/¯

2022-03-06 15:28 UTC, f0rsakenOne commented on src/main/java/io/codelex/loops/exercises/FizzBuzz.java
> +            if (j % 20 == 0 && j % 3 == 0) {
kaut kā neizdomāja izmantot otru if, ar viņu izskatās daudz skaistāk

2022-03-06 15:35 UTC, f0rsakenOne commented on src/main/java/io/codelex/loops/exercises/NumberSquare.java
> +        for (int i = min;i<=max;i++){
Es pilnībā nesapratu, ko jūs domājāt, bet es noņēmu lieku mainīgo un izveidoju atsevišķu metodu, kas return string ar šiem skaitliem.

2022-03-06 15:38 UTC, f0rsakenOne commented on src/main/java/io/codelex/loops/exercises/Piglet.java
> +                System.out.println("You got "+score+" points.");
noņēma šīs rindas un izmainiju lai izvādas pēc cikla

2022-03-13 10:13 UTC, janistumpelis approved these changes

2022-03-14 13:55 UTC, merged