Arrays
f0rsakenOne/home-excercises pull request #3
Opened 2022-03-04 02:25 UTC by f0rsakenOne

atvainojos par šo nekārtību kodā

2022-03-10 19:55 UTC, NilsKula requested changes

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/exercises/Exercise6.java
> +        for (int i =0 ; i<numbers.length;i++){
te varētu vienkāršot, ka updeito vienkārši pēdējo elementu

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +    //atvainojos par šo nekārtību
:laughing:

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +    private static final String[] words = {"important", "spine", "departure", "concrete", "intermediate", "integrity", "money","portrait","tray","point","top"};
baigi gara rinda sanāk, java line length convention ~100 characters
labāk sadalīt uz vaiākām rindām

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +        } else System.out.println("You lost :(");
curly braces

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +
formatting: ar vienu tukšu līniju pilnīgi arī pietiktu :smile:

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +public class Exercise8 {
baigi labi, ka sadalīji tik sīki metodes
vienīgi varbūt viņu secība nedaudz, piemēram, `newGame()` izsauc `initSlashes()` tad slashes būtu zem
un vnk `spaces` formatting dažviet, try `ctrl + alt + l` i think i should help

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/practice/Exercise2.java
>      public static void main(String[] args) {
ja ievadu 8 un 9, nedabūju 17 :/

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +    public static void changeTiles() {
palīgmetodes private, gluži kā 8. uzdevumā jau izdarīji

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +        boolean tie = false;
šo jau laikam var izdzēst

2022-03-10 19:55 UTC, NilsKula commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +        //horizontal win
var kaut vai tad šos arī sadalīt pa metodēm `checkHorizontalWin()` utt, lai izvairītos komentāriem

2022-03-14 12:48 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/exercises/Exercise6.java
> +        for (int i =0 ; i<numbers.length;i++){
jā, tas būtu vieglāk

2022-03-14 12:49 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +    private static final String[] words = {"important", "spine", "departure", "concrete", "intermediate", "integrity", "money","portrait","tray","point","top"};
salaboja to

2022-03-14 12:49 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +        } else System.out.println("You lost :(");
salaboja to

2022-03-14 12:49 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +
salaboja to

2022-03-14 12:53 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/exercises/Exercise8.java
> +public class Exercise8 {
salaboja to, lai izskatītos skaistāk

2022-03-14 12:56 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +    public static void changeTiles() {
Visu nomainīja uz privātu

2022-03-14 12:57 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +        boolean tie = false;
izdzēsa to

2022-03-14 12:57 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +        //horizontal win
sadalīja šo metodi trīs atsevišķās daļās

2022-03-15 17:24 UTC, NilsKula approved these changes

2022-03-18 22:43 UTC, f0rsakenOne commented on src/main/java/io/codelex/arrays/practice/TicTacToe.java
>          boolean win = false;
mainīja tos mainīgos

2022-03-18 22:43 UTC, merged