Classes and objects
f0rsakenOne/home-excercises pull request #4
Opened 2022-03-09 00:51 UTC by f0rsakenOne

esmu izpildījis visus uzdevumus, bet nezinu, vai bija nepieciešams katrai klasei izveidot atsevišķu klasi ar galveno metodi, un es katrā klasē izveidoju galveno metodi, bet pirms pārbaudīju, vai galveno metodi var saukt no atsevišķa klase.

2022-03-17 13:34 UTC, NilsKula requested changes

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Car.java
> +        return (100/calculateConsumption()) > 15;
15 - constant

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Odometer.java
> +        if (mileage<MAX_MILEAGE){
`ctrl + alt + L` for styling

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/FuelGauge.java
> +            currentFuel = 70;
`currentFuel = MAX_FUEL`

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Odometer.java
> +    public void incrementOdometer(){
domaju šeit labak vari padot `incrementOdometer(FuelGauge fuelGauge)`

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Date.java
> +        if (day > 0 && day <= 31) {
šie tev atkārtojas, nice to have, izvilkt uz mazo palīgmetodi piemēram `isValidDay`

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        return father;
šeit biški pa daudz lieku rindu
vari pa taisno atgriet un neradīt papildus variable
`return Objects.requireNonNullElse(this.nameOfFather, "Unknown")`

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        return Objects.equals(this.nameOfMother, otherDog.nameOfMother);
handle null mother

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        System.out.println(max.toString());
varētu visus suņus salikt listā un tad caur loop izprintēt

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        Dog max = new Dog("Max", "male", "Rocky", "Lady");
gender, great place to use enum

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/SavingsAccount.java
> +    public SavingsAccount(double balance) {
konstruktoru labāk pirms visiem getteriem/setteriem un citam metodēm

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/SavingsAccount.java
> +        System.out.printf("Interest earned: $%,.2f %n" , person1.getBalance()-person1.getTotalDeposited()-person1.getTotalWithdrawn());
baigi gara rinda :smile: varētu noteikti labāk uz `double = interestEarned` izvlikt

2022-03-17 13:34 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/practice/BankAccount.java
> +        String str = "";
arī vari izlaist, un likt vienkārši `return` vietās kur seto so vertību

2022-03-18 22:15 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Odometer.java
> +        if (mileage<MAX_MILEAGE){
cerams, ka es nekad neaizmirsīšu to izdarīt pirms katra push 😅

2022-03-18 22:18 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/FuelGauge.java
> +            currentFuel = 70;
hah, tā būtu labāk

2022-03-18 22:21 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Odometer.java
> +    public void incrementOdometer(){
salabojis to

2022-03-18 22:22 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Date.java
> +        if (day > 0 && day <= 31) {
pievienotas arī pārbaudes metodes gadam un mēnesim

2022-03-18 22:26 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        Dog max = new Dog("Max", "male", "Rocky", "Lady");
toreiz nezināja, kas ir enums, bet tagad salaboja

2022-03-18 22:26 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/SavingsAccount.java
> +    public SavingsAccount(double balance) {
salabojis to

2022-03-18 22:27 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/SavingsAccount.java
> +        System.out.printf("Interest earned: $%,.2f %n" , person1.getBalance()-person1.getTotalDeposited()-person1.getTotalWithdrawn());
izveidoja metodi, kas to darīs

2022-03-18 22:28 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        System.out.println(max.toString());
salabojis to

2022-03-18 22:28 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Car.java
> +        return (100/calculateConsumption()) > 15;
salabojis to

2022-03-18 22:32 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        return father;
fixed, toreiz es domāju , ka tā ir "labāk".

2022-03-18 22:32 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/practice/BankAccount.java
> +        String str = "";
fixed

2022-03-18 22:38 UTC, f0rsakenOne commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        return Objects.equals(this.nameOfMother, otherDog.nameOfMother);
tagad vajadzētu būt ok

2022-03-20 11:37 UTC, NilsKula commented on src/main/java/io/codelex/classesandobjects/exercise/Dog.java
> +        Dog max = new Dog("Max", "male", "Rocky", "Lady");
my bad 😬

2022-03-20 11:37 UTC, NilsKula approved these changes

2022-03-20 12:35 UTC, merged