finished enums and maps exercises
f0rsakenOne/home-excercises pull request #7
Opened 2022-03-21 21:58 UTC by f0rsakenOne

2022-03-23 11:19 UTC, NilsKula requested changes

2022-03-23 11:19 UTC, NilsKula commented on src/main/java/io/codelex/enums/practice/RockPaperScissorsGame.java
> +    private static int playerWins = 0;
why static? :thinking:

2022-03-23 11:19 UTC, NilsKula commented on src/main/java/io/codelex/enums/practice/RockPaperScissorsGame.java
> +    public static void getAiMove() {
private

2022-03-23 11:19 UTC, NilsKula commented on src/main/java/io/codelex/enums/practice/RockPaperScissorsGame.java
> +    public static void getResult() {
confusing naming a bit, void metode bet ar `get()`

2022-03-23 11:19 UTC, NilsKula commented on src/main/java/io/codelex/enums/practice/RockPaperScissorsGame.java
> +                    System.out.println("\tYou won!");
```
System.out.println("\tYou won!");
playerWins++;
trials++;
```
šī daļa, piemēram atkārtojas 3x

2022-03-25 16:19 UTC, f0rsakenOne commented on src/main/java/io/codelex/enums/practice/cardinalPoints.java
> +public enum cardinalPoints {
fixed

2022-03-25 16:19 UTC, f0rsakenOne commented on src/main/java/io/codelex/enums/practice/RockPaperScissorsGame.java
> +    public static void getAiMove() {
fixed

2022-03-25 16:26 UTC, f0rsakenOne commented on src/main/java/io/codelex/enums/practice/RockPaperScissorsGame.java
> +                    System.out.println("\tYou won!");
izveidoja divas palīgmetodes, kas pārbauda, vai ai uzvar vai spēlētājs uzvar

2022-03-27 07:07 UTC, NilsKula approved these changes

2022-03-27 15:13 UTC, merged