Collections
f0rsakenOne/home-excercises pull request #9
Opened 2022-03-25 19:07 UTC by f0rsakenOne

2022-04-10 14:58 UTC, NilsKula requested changes

2022-04-10 14:58 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +                .filter((String x) -> x.split("->")[0].contains(city))
`(String x)` lieki -> `.filter(flight -> flight.split("->")[0].contains(city))`

2022-04-10 14:58 UTC, NilsKula commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectory.java
> +            return data.get(position).number;
ārpus klases geteri izmanto `.getNumber()`

2022-04-12 15:36 UTC, f0rsakenOne commented on src/main/java/io/codelex/collections/practice/FlightPlanner.java
> +                .filter((String x) -> x.split("->")[0].contains(city))
fixed it

2022-04-12 15:40 UTC, f0rsakenOne commented on src/main/java/io/codelex/collections/practice/phonebook/PhoneDirectory.java
> +            return data.get(position).number;
.getNumber() vietā es nomainīju, lai tas saņemtu phoneEntry un izveidotu getterus un setterus phoneEntry

2022-04-15 17:51 UTC, NilsKula approved these changes

2022-04-18 12:45 UTC, merged